---

- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Set timezone
  shell:
    timedatectl set-timezone Asia/Tokyo

- name: Update the package list
  apt:
    update_cache: "yes"

- name: Upgrade the package
  apt:
    upgrade: "yes"

- name: Install some packages
  apt:
    name:
      - vim
      - ansible
      - sshpass
      - curl
      - unzip
      - jq

