---

- name: Create /etc/prometheus/alertmanager directory
  shell: |
    mkdir -p /etc/prometheus/alertmanager

- name: Create /var/lib/prometheus/alertmanager/data directory
  shell: |
    mkdir -p /var/lib/prometheus/alertmanager/data

- name: Create alertmanager.yml
  template:
    src: "alertmanager.yml.j2"
    dest: "/etc/prometheus/alertmanager/alertmanager.yml"

- name: Create slack_templates.tmpl
  template:
    src: "slack_templates.tmpl"
    dest: "/etc/prometheus/alertmanager/slack_templates.tmpl"

- name: Create slack_template_url.tmpl
  template:
    src: "slack_template_url.tmpl"
    dest: "/etc/prometheus/alertmanager/slack_template_url.tmpl"

- name: Create alertmanager.service
  template:
    src: "alertmanager.service.j2"
    dest: "/etc/systemd/system/alertmanager.service"

- name: Deploy Alertmanager
  shell: |
    chown -R prometheus:prometheus /var/lib/prometheus/alertmanager/data
    systemctl daemon-reload
    systemctl enable  alertmanager.service
    systemctl restart alertmanager.service

