---

- name: Install blackbox_exporter
  shell: |
    wget https://github.com/prometheus/blackbox_exporter/releases/download/v{{ BlackboxExporter.Version }}/blackbox_exporter-{{ BlackboxExporter.Version }}.linux-arm64.tar.gz
    tar -xzvf blackbox_exporter-{{ BlackboxExporter.Version }}.linux-arm64.tar.gz
    cp blackbox_exporter-{{ BlackboxExporter.Version }}.linux-arm64/blackbox_exporter /usr/local/bin/
    setcap cap_net_raw+ep /usr/local/bin/blackbox_exporter
    rm -r blackbox_exporter-{{ BlackboxExporter.Version }}.linux-arm64
    rm    blackbox_exporter-{{ BlackboxExporter.Version }}.linux-arm64.tar.gz

