---

- name: Configure modules
  shell: |
    sh -c "cat > /etc/modules-load.d/k8s.conf <<EOF
    overlay
    br_netfilter
    EOF"
    modprobe overlay 
    modprobe br_netfilter

- name: Configure sysctl.d
  shell: |
    sh -c "cat > /etc/sysctl.d/99-kubernetes-cri.conf <<EOF
    net.bridge.bridge-nf-call-iptables  = 1
    net.ipv4.ip_forward                 = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    fs.inotify.max_user_watches         = 20480
    EOF"
    sysctl --system

- name: Update the package list
  apt:
    update_cache: "yes"

- name: Install some packages
  apt:
    name:
      - iptables
      - arptables
      - ebtables
      - containerd
      - runc
      - gnupg2
      - apt-transport-https
      - curl

- name: Configure update-alternatives
  shell: |
    update-alternatives --set iptables /usr/sbin/iptables-legacy
    update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy
    update-alternatives --set arptables /usr/sbin/arptables-legacy
    update-alternatives --set ebtables /usr/sbin/ebtables-legacy

- name: Configure containerd
  shell: |
    mkdir -p /etc/containerd
    containerd config default | sudo tee /etc/containerd/config.toml
    sed -i s/"SystemdCgroup = false"/"SystemdCgroup = true"/g /etc/containerd/config.toml

- name: Restart containerd
  systemd:
    name: containerd
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: Upgrade containerd & runc
  shell: |
    wget https://github.com/containerd/containerd/releases/download/v1.6.6/containerd-1.6.6-linux-arm64.tar.gz
    tar Cxzvf /usr/local containerd-1.6.6-linux-arm64.tar.gz
    rm containerd-1.6.6-linux-arm64.tar.gz
    wget https://github.com/opencontainers/runc/releases/download/v1.1.3/runc.arm64
    mv ./runc.arm64 ./runc
    chmod +x ./runc
    mv ./runc /usr/local/bin
    mv /usr/local/bin/containerd /usr/bin/containerd
    mv /usr/local/bin/runc       /usr/bin/runc

- name: Restart containerd
  systemd:
    name: containerd
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: Add k8s package list
  shell: |
    curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
    cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
    deb https://apt.kubernetes.io/ kubernetes-xenial main
    EOF

- name: Update the package list
  apt:
    update_cache: "yes"

- name: Install kubelet, kubeadm and kubectl
  apt:
    name:
      - kubelet={{ Kubernetes.Version }}-00
      - kubeadm={{ Kubernetes.Version }}-00
      - kubectl={{ Kubernetes.Version }}-00

- name: Change kubelet config file
  template:
    src: "10-kubeadm.conf.j2"
    dest: "/etc/systemd/system/kubelet.service.d/10-kubeadm.conf"

- name: Restart kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    enabled: yes
    state: restarted

- name: Hold kubeadm
  dpkg_selections:
    name: kubeadm
    selection: hold

- name: Hold kubelet
  dpkg_selections:
    name: kubelet
    selection: hold

- name: Hold kubectl
  dpkg_selections:
    name: kubectl
    selection: hold

