---

- name: Execute ssh-copy-id
  shell: |
    sshpass -p {{ password }} ssh-copy-id {{ item }} -o StrictHostKeyChecking=no
  with_items:
    - "{{ groups['k8s-loadbalancers'] }}"
    - "{{ groups['k8s-control-planes'] }}"
    - "{{ groups['k8s-nodes'] }}"
    - "{{ groups['monitoring-servers'] }}"

