---

- name: Set hostname
  shell: |
    hostnamectl set-hostname {{ inventory_hostname }}

- name: Edit /etc/crontab
  lineinfile:
    path: /etc/crontab
    line: "@reboot sudo hostnamectl set-hostname {{ inventory_hostname }}"

- name: Set timezone
  shell:
    timedatectl set-timezone Asia/Tokyo

- name: Update the package list
  apt:
    update_cache: "yes"

- name: Upgrade the package
  apt:
    upgrade: "yes"

- name: Install some packages
  apt:
    name:
      - vim
      - unzip
      - jq
      - ansible
      - sshpass
      - golang-cfssl

