Environment: raspi-k8s
Kubernetes:
  Version: 1.24.3                         # インストールするKubernetesのバージョンを指定
  PodNetworkCIDR: 192.168.0.0/18          # Pod NetworkのCIDRを指定
  NodeNetworkCIDR: 192.168.114.0/24       # Node NetworkのCIDRを指定
  ClusterName: raspi-k8s                  # Kubernetessクラスタの名前を指定
MonitoringServer:
  Keepalibed:
    VirtualLocalIPAddress: 192.168.111.10 # 監視サーバのVIPを指定
LoadBalancer:
  Hostname: raspi-k8s-control-plane.home.arpa   # ロードバランサのホスト名を指定
  BindPort: 64430                         # ロードバランサのポートを指定
  Keepalived:
    VirtualLocalIPAddress: 192.168.114.10 # K8s Node Network側kube-apiserver用ロードバランサのVIPを指定
Consul:
  Version: 1.12.3
Prometheus:
  Version: 2.37.0
  BaseURL: http://prometheus.home.arpa
Alertmanager:
  Version: 0.24.0
  BaseURL: http://alertmanager.home.arpa
BlackboxExporter:
  Version: 0.21.1
NodeExporter:
  Version: 1.3.1
